publish:
  include:
    - stage: npm release
      node_js: "12.13"
      branchs:
        only:
          - master
      cache:
        directories:
          - node_modules
      script:
        - echo "skipping tests"
      install:
        - yarn install
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master