jobs:
  include:
    - stage: npm release
      node_js: "12.13"
      script: ehco "hello word"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master